# Generated by Django 2.1.2 on 2019-01-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.IntegerField()),
                ('previous_hash', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(default=1548883432.432183)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('address', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=1548883432.434081)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=300)),
                ('recipient', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('timestamp', models.DateTimeField(default=1548883432.433078)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain_app.Block')),
            ],
        ),
    ]
